### ISSUE TITLE
Amazon MemoryDB for Redis: LoadPolicy() got errror "The type is wrong"

### ISSUE THREAD

**Issue by hongtran96** [casbin/redis-adapter#42]
## Problem
I have two Casbin enforcer instances. I use RedisWatcher to notify others of the changes in policies. 
After receiving the notification, the instance will load the policy to get the latest model. 

However, LoadPolicy() is getting a `The type is wrong` error.

## Env
- Casbin Redis adapter: v3.2.1
- Casbin v2.66.1
- Amazon MemoryDB for Redis

Does anybody have any idea of this issue? Thank you.

**Comment by MuZhou233** [comment]
I believe this problem is related to the set policy processes. Here you could see the error is caused by broken value in redis. 
https://github.com/casbin/redis-adapter/blob/9c324f034643b8f0fa479054b84b57d615c9c5bd/adapter.go#L240-L249

Does this error occured right after you call `SavePolicy`, or after modified with add and remove functions? Do you use two instances to set and modify policies at the same time? It would be useful if you can provide a reproduction.

**Comment by hongtran96** [comment]
> occured right after you call `SavePolicy`, or after modified with add and remove functions? Do you use two instances to set and mod

I believe that Amazon MemoryDB for Redis causes this. 
I ran my application with Redis in both standalone and cluster mode, LoadPolicy() worked well, but Amazon MemoryDB for Redis. 
Amazon MemoryDB returns `string` instead of `[]byte`.
